### ISSUE TITLE
Memoページについて

### ISSUE THREAD

**Issue by mizushima1226** [yiinuma/React-MemoApp_Next.js#1]
src/pages/Memo.tsx
の部分ですが、URLの命名はケバブケースが良いとされています
ref: https://off.tokyo/blog/kebab-case-url/

Reactのコンポーネントファイルは大文字で始める、という慣習がありますが、
Next.jsのpages配下はそのままURLに反映されるので例外的ですが、ケバブケースでファイルを命名すると良いです🙆‍♂️

軽微な修正なので対応出来次第連絡なしにこのissueをcloseしていただいてOKです👍

**Comment by yiinuma** [comment]
Memoをケバブケースに修正しました
